### ISSUE TITLE
Latest version not working in IE11

### ISSUE THREAD

**Issue by shailee-m** [jbaysolutions/vue-grid-layout#502] opened 2020-11-23 08:35 UTC
**Software version:**
 - Browser: IE11
 - Vue Version: 2.6.12
 - vue-grid-layout Version: 2.3.11

**Description**
When using vue-grid-layout in IE11, it throws a syntax error. `var v = t=>!(!t || !t.Window) && t instanceof t.Window`
This sentence reported an error in ie11 browser

Same as #495 

![b22bb33d-3086-4b28-8900-064ad436c6b0](https://user-images.githubusercontent.com/10625985/99941791-a1545380-2d94-11eb-9e30-51fc30396ef8.png)

**Comment by gmsa** [comment] 2020-11-23 09:51
duplicate of #499 , already answered there

**Closed by gmsa** 2020-11-23 09:51 UTC

**Comment by gmsa** [comment] 2021-01-15 18:16
Version 2.3.12-legacy supports IE
