### ISSUE TITLE
An error occurred when the component was introduced ：You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by kkueo123456** [jbaysolutions/vue-grid-layout#507] opened 2020-11-24 09:12 UTC
Module parse failed: Unexpected token (10332:31)
You may need an appropriate loader to handle this file type.
| subModification.prepareStates(modifiers);
| state.subModification = subModification;
| subModification.startAll({ ...arg
| });
| },

**Comment by yihuoren** [comment] 2020-12-08 11:40
We have the same problem

**Comment by yihuoren** [comment] 2020-12-08 11:41
2.3.11

**Comment by gmsa** [comment] 2020-12-18 09:55
duplicate of #488

**Closed by gmsa** 2020-12-18 09:55 UTC

**Comment by gmsa** [comment] 2021-01-15 18:22
Version 2.3.12-legacy shouldn't have these issues
