### ISSUE TITLE
interact.js

### ISSUE THREAD

**Issue by MironenkoDeveloper** [jbaysolutions/vue-grid-layout#572] opened 2021-03-03 15:27 UTC
Hi, how do I fix this error ?
![Screenshot 2021-03-03 at 18 25 48](https://user-images.githubusercontent.com/35580366/109828764-fcc49600-7c4d-11eb-926d-4c0381bbdd22.png)

**Comment by MironenkoDeveloper** [comment] 2021-03-03 17:13
![Uploading Screenshot 2021-03-03 at 20.12.51.png…]()

**Comment by MironenkoDeveloper** [comment] 2021-03-03 17:14
I can't set the environment in the project 
<img width="788" alt="Screenshot 2021-03-03 at 20 12 51" src="https://user-images.githubusercontent.com/35580366/109844209-f7bb1300-7c5c-11eb-9486-a1ec2a30e1b9.png">

**Comment by MironenkoDeveloper** [comment] 2021-03-03 17:33
Hi @gmsa I need your help

**Comment by gmsa** [comment] 2021-03-03 17:36
duplicate of #573

**Closed by gmsa** 2021-03-03 17:36 UTC
