### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by MironenkoDeveloper** [jbaysolutions/vue-grid-layout#550] opened 2021-01-23 08:24 UTC
When is it planned to add support for VUE 3? I am currently planning to use your library for a project. Thanks.

**Comment by gmsa** [comment] 2021-01-25 10:45
There is a vue3 branch already, but haven't tested it yet to make a release.

**Comment by gmsa** [comment] 2021-01-25 17:10
Duplicate of #439

**Closed by gmsa** 2021-01-25 17:10 UTC
