### ISSUE TITLE
An error occurred when the component was introduced ：You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by RookieCockWire** [jbaysolutions/vue-grid-layout#519] opened 2020-12-18 02:20 UTC
**Software version (please complete the following information):**
 - Browser [chrome, safari]
 - Vue Version [e.g. 2.5.7]
 - vue-grid-layout Version: [e.g. 2.3.6]

**Describe the bug**

**Comment by gmsa** [comment] 2020-12-18 09:55
duplicate of #488

**Closed by gmsa** 2020-12-18 09:55 UTC
